services:
  - type: web
    name: nonfryer_recipes
    env: ruby
    buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bin/rails db:migrate;
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-10000} -e ${RACK_ENV:-development}
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: "2"
